name: primeira-pipeline
on:
  push: 
    branches: ["main"]
  workflow_dispatch:
jobs:
  primero-job:
    name: "meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "minha primeira ação"
        run: echo "Hello World!!!"
      - name: "Segunda ação"
        run: |
          echo "Primeiro worflow"
          echo "deu certinho"
  segundo-jobs:
    name: "segundo job"
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install


      - name: Run tests
        run: npm test   
  
