name: primeira-pipeline
on:
  push: 
    branches: ["main"]
  workflow_dispatch:
jobs:
  primero-job:
    name: "meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "minha primeira ação"
        run: echo "Hello World!!!"
      - name: "Segunda ação"
        run: |
          echo "Primeiro worflow"
          echo "deu certinho"
  segundo-jobs:
    name: "segundo job"
    runs-on: ubuntu-latest
    steps:
      - name: "verificacao node atual"
        run: node --version
        
      - name: "Atualizando versao do node js"
      - uses: actions/setup-node@v4.0.2
        with: 
          node-version: '20.31.1'

      - name: "verificacao node  depois de instalar"
        run: node --version 
  
